### ISSUE TITLE
React global not correct in v0.9.5

### ISSUE THREAD

**Issue by nijk** [souporserious/react-popper#133]
### Steps to reproduce the problem

1.  Unpackage and run `dist/react-popper.js`
2.  See that the JS interpreter fails on line 132: `react.Component`
```
Uncaught TypeError: Cannot read property 'Component' of undefined
```

### What is the expected behavior?

I'd expect the React global to be referenced with a capital R.

### What went wrong?

Possibly something in the Rollup globals, I see a commit in the last 24hours that suggests a fix to UMD globals but can't see that this fix works for either UMD or the standard builds.

### Packages versions

- Popper.js: 1.14.1
- react-popper: 0.9.5

**Comment by FezVrasta** [comment]
Hi, `dist/react-popper.js` is a CommonJS build, and it refers to react with the lowercase `r` because that's its package name.

UMD build is `dist/react-popper.umd.js`, and it refers to `React` with capital `r` because that's its global namespace in browser environments:

```
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('react'), require('prop-types'), require('popper.js')) :
  typeof define === 'function' && define.amd ? define(['exports', 'react', 'prop-types', 'popper.js'], factory) :
  (factory((global.ReactPopper = {}),global.React,global.PropTypes,global.Popper));
}(this, (function (exports,react,PropTypes,PopperJS) { 'use strict';
```

Internally, the library refers to `react` with lowercase `r`, but it is assigned to `global.React` (capital)

**Comment by FezVrasta** [comment]
I'm not sure why you are getting this error, I'd try to put a `console.log(React)` just before the `react-popper.umd.js` import to see what it logs. If it's empty, you have some problem in the react import.

**Comment by nijk** [comment]
Ok, thanks for the quick responses
