### ISSUE TITLE
Warning if passing to Manager unknown props

### ISSUE THREAD

**Issue by davelab** [souporserious/react-popper#68]
Hi,
referring to this issue in styled-component repo.
https://github.com/styled-components/styled-components/issues/1268

I was wondering how can I avoid that unknown props will be passed to Manager's div.
I need to pass these properties in order to use it in a style js conf file for styled-component element.

https://www.webpackbin.com/bins/-KxN8G3pDI0nHJTNmExw

and like you suggested if I set tag={false} it retrieves me this error:

`Uncaught Invariant Violation: Manager.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.`

**Comment by souporserious** [comment]
Sorry, just getting to this. Since React 16 has shipped since this issue 😅 you should be able to use `Manager tag={false}` safely now. If you're still on an older version of React, you can add a wrapping element since earlier versions can't return arrays. If you need even further customization/rendering control, you can use [child functions](https://github.com/souporserious/react-popper#usage-w-child-function).
