### ISSUE TITLE
Remove Prop-Types from Production Build

### ISSUE THREAD

**Issue by virgofx** [souporserious/react-popper#80]
It would be nice if PropTypes wasn't in the production build in any fashion. I believe this could be achieved by utilizing the following plugin:

https://www.npmjs.com/package/babel-plugin-transform-react-remove-prop-types

This would allow using the library without having to include the prop-types library as a pre-requisite in production.

**Comment by FezVrasta** [comment]
That would be cool, feel free to send a PR also!

**Comment by Justkant** [comment]
Hi,
If you're talking about the umd build, I think that the prop-types module is mark as external and so not included there.
But if not, I don't think that the library should do that but you clearly should use this plugin for your app in production.

As said in #91 
Recommended way for libraries: https://github.com/facebook/prop-types#how-to-depend-on-this-package
Also: https://github.com/facebook/prop-types/issues/44

**Comment by virgofx** [comment]
1. I am referring to the UMD build.
2. You are wrong in your assumptions on how external works. That refers to whether the referenced library is included.
This PR is in regards to the use of Prop-Types ... it should make use of the remove prop types plugin as numerous other application libraries do allowing inheriting apps to not have a required dependency in production.

**Comment by Justkant** [comment]
Got you, so we should strip prop-types for the minified version of the umd build ?

**Comment by virgofx** [comment]
Yes. Not necessarily "strip" but use the proper mode (I believe wrap) with the plugin to remove as much as possible and where appropriate transforms certain situations to `{}` where constants dot-walks won't fail. ... Effectively removing as much as possible such that a referenced application does not need to either manually include `prop-types` for this to work.

**Comment by Justkant** [comment]
Ok the need to include `prop-types` is there because we use externals with the webpack conf, by removing `prop-types` from the externals you don't need to manually include it anymore.
But the size of the bundle is bigger even in the production build (I thought that uglify could remove the dead_code and so the `prop-types`).
What would be the prefered result here ? Not having to include `prop-types` using the umd build even with a bigger module size ?

**Comment by virgofx** [comment]
The original issue outlines everything in detail. Please read up on how things work.

1 - `prop-types` should be listed as external. This allows consuming applications to handle as necessary and the distribution builds will EXCLUDE the `prop-types` library. This is desired.

2 - However, References to prop types inside the library are now unnecessary and have references to constants used by the `prop-types` library. This is not needed in production as it requires an additional include for applications that don't already include the prop-types in production (most don't).  Additionally, it results in extra code and large dist size.

Please read up on prop types, before continuing any further in this thread.

**Comment by Justkant** [comment]
I understand that, I already took some time yesterday to add the babel-plugin that I also use on almost all my react projects.

The part were I'm a bit confused is related to the use of the UMD build. (Maybe an example could help me there)

Also if you can find a repo that is already setup the way want please share it because on all the repos that I looked at no one was making the `prop-types` as external.

**Comment by Justkant** [comment]
A problem for this lib would be [this issue](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/issues/77)
One solution would be to handle contextTypes & childContextTypes ourself, like so:
```js
Arrow.contextTypes = process.env.NODE_ENV !== "production" ? {
  popper: PropTypes.object.isRequired,
} : {
  popper: () => {},
}
```

**Comment by FezVrasta** [comment]
What if we simply wait for the new context API? Once we get it we'll be able to get rid of PropTypes all together

**Comment by Justkant** [comment]
@FezVrasta yeah I thought about waiting for the new context API too, but if @virgofx doesn't want to wait #94 is still a solution.

I wonder if after the refactoring for the new context we'll be able to support the old context.
An idea on this subject too ?

**Comment by virgofx** [comment]
@Justkant The plugin prevents writing code which you did. I haven't had time to test; however, it's literally as simple as marking prop-types as external, and using the preset for all builds with appropriate flags (mode:wrap). It still should leave in context and a few other areas (That's what needs to be tested).

Sample **Library**
[Material-UI](https://github.com/mui-org/material-ui/blob/v1-beta/.babelrc)

**Comment by Justkant** [comment]
@virgofx You're right and if you take a look at #94 you can see the `prop-types` plugin in use. (with the mode: wrap)

Also for the contextTypes & childContextTypes that are not handle by the plugin, I followed the [test](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/pull/98#issuecomment-335994196) of someone else

I also tested everything from jsfiddle to be sure it was working without the `prop-types` ([new](https://jsfiddle.net/p9pnbup3/2/) vs [old](https://jsfiddle.net/2r7sLeqn/1/) -- look at the console)

🤣Material-UI was one of the lib that I looked at but they're not using externals for `prop-types` ([umd webpack conf](https://github.com/mui-org/material-ui/blob/v1-beta/scripts/umd.webpack.config.js)) 
That's why I was asking for it in the first place.
